server:
  port: 8084 # As defined in your Service Matrix

spring:
  application:
    name: muscledia-ai-service
  ai:
    openai:
      base-url: http://model-runner:12434/engines
      api-key: ignored
      chat:
        options:
          model: ai/llama3.2:3B-Q4_K_M
          temperature: 0.5
    model:
      chat: openai
      embedding:
        enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://service-discovery:8761/eureka # Point to Eureka Server
  instance:
    prefer-ip-address: true
    hostname: ai-service


# JWT Configuration
jwt:
  secret: ${JWT_SECRET:81795ad725b2cadd49d27a60438415588db374020a561ae19cafebeef6339655304975b150867b21d3715e341a49271a75a7dde39776e156af0ddad50f5e6ec3}
  expiration: ${JWT_EXPIRATION:86400000} # 24 hours in milliseconds
  issuer: ${JWT_ISSUER:muscledia-user-service}

